### ISSUE TITLE
Persist contract with large capability 

### ISSUE THREAD

**Issue by devus10** [HLTech/judge-d#28]
Currently, it's impossible to add contract with large capability. When I tried to add contract with swagger docs having about ~1.7M characters, I received following exception:

`org.postgresql.util.PSQLException: ERROR: value too long for type character varying(65436)
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2455)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2155)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:288)
	at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:430)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:356)
	at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:168)`

**Comment by Felipe444** [comment]
Done
